app = "grafana-miao-dev"
primary_region = "ewr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "grafana/grafana"

[env]
  GF_INSTALL_PLUGINS = "grafana-worldmap-panel,grafana-clock-panel"
  GF_SERVER_DOMAIN = "grafana.miao.dev"
  GF_SERVER_PROTOCAL = "https"
  GF_SERVER_ROOT_URL = "https://grafana.miao.dev/"

[[mounts]]
  source = "grafana_machines"
  destination = "/var/lib/grafana"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/api/health"
    protocol = "http"
